name: Push commit
on:
  push:
  schedule:
    - cron: "0 0 * * *"
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Create report file
        run:  |
          pip install lxml
          python freeTaps_gpx_convert.py
      - name: Commit report
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'varlorg@users.noreply.github.com'
          git commit -am "Automated FreeTaps GPX generation"
          git push
