name: Update GPS file
on:
  push:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Create FreeTaps file
        run:  |
          pip install lxml
          python freeTaps_export.py
      - name: Commit FreeTaps
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'varlorg@users.noreply.github.com'
          git add --update
          git diff-index --quiet HEAD || git commit -m "Automated FreeTaps GPX export" 
          git push
      - name: Create eaupotable file
        run:  |
          pip install lxml
          python eaupotable-info_export.py
      - name: Commit eaupotable
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'varlorg@users.noreply.github.com'
          git add --update
          git diff-index --quiet HEAD || git commit -m "Automated eaupotable.info GPX export" 
          git push
