name: Push commit
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Create report file
        run: python freeTaps_gpx_convert.py
      - name: Commit report
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'varlorg@users.noreply.github.com'
          git commit -am "Automated FreeTaps GPX generation"
          git push
